### ISSUE TITLE
Benchmark throw exception: Failed to retrieve class for com.oltpbenchmark.benchmarks.tpcc.procedures.AddWatchList

### ISSUE THREAD

**Issue by vadv** [oltpbenchmark/oltpbench#100]
```
postgres@pg-test:~/oltpbench$ ant
Buildfile: /home/postgres/oltpbench/build.xml

build:
    [mkdir] Created dir: /home/postgres/oltpbench/build/META-INF
     [copy] Copying 1 file to /home/postgres/oltpbench/build/META-INF
    [javac] Compiling 362 source files to /home/postgres/oltpbench/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 warning
     [copy] Copying 89 files to /home/postgres/oltpbench/build
    [mkdir] Created dir: /home/postgres/oltpbench/build/tests
    [javac] Compiling 50 source files to /home/postgres/oltpbench/build/tests
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] 1 warning

BUILD SUCCESSFUL
Total time: 8 seconds
postgres@pg-test:~/oltpbench$ ./oltpbenchmark -b tpcc -c config/sample_wiki_config.xml --create=true --load=true
12:32:35,232 (DBWorkload.java:242) INFO  - **********************************************************************************

Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: config/sample_wiki_config.xml
Type:          MYSQL
Driver:        com.mysql.jdbc.Driver
URL:           jdbc:mysql://server:3306/ycsb
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  100.0

12:32:35,233 (DBWorkload.java:243) INFO  - **********************************************************************************
Exception in thread "main" java.lang.RuntimeException: Failed to retrieve class for com.oltpbenchmark.benchmarks.tpcc.procedures.AddWatchList
        at com.oltpbenchmark.util.ClassUtil.getClass(ClassUtil.java:275)
        at com.oltpbenchmark.api.BenchmarkModule.initTransactionType(BenchmarkModule.java:360)
        at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:269)
Caused by: java.lang.ClassNotFoundException: com.oltpbenchmark.benchmarks.tpcc.procedures.AddWatchList
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.oltpbenchmark.util.ClassUtil.getClass(ClassUtil.java:273)
        ... 2 more
postgres@pg-test:~/oltpbench$ java -version
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by dedcode** [comment]
You have loaded the TPCC benchmark, using the sample_wiki_config.xml which is for Wikipedia benchmark.
Please use sample_tpcc_config.xml instead.

**Comment by vadv** [comment]
Thank you for your answer!
How i can run sample_pgtpcc_config benchmark?
```
postgres@pg-test:~/oltpbench$ psql -h diuflx01 -p 5432 -Atc 'select now()'
2015-06-18 17:23:35.622336+03
postgres@pg-test:~/oltpbench$ ./oltpbenchmark -b tpcc -c config/sample_pgtpcc_config.xml --create=true --load=true
17:23:40,494 (DBWorkload.java:242) INFO  - **********************************************************************************

Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: config/sample_pgtpcc_config.xml
Type:          POSTGRES
Driver:        org.postgresql.Driver
URL:           jdbc:postgresql://diuflx01:5432/tpcc/
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  1.0

17:23:40,498 (DBWorkload.java:243) INFO  - **********************************************************************************
17:23:40,505 (BenchmarkModule.java:351) ERROR - Procedure tpcc.INVALID cannot the reserved id '0' for TransactionType
Exception in thread "main" java.lang.RuntimeException: Failed to retrieve class for com.oltpbenchmark.benchmarks.tpcc.procedures.NEW_ORDER
        at com.oltpbenchmark.util.ClassUtil.getClass(ClassUtil.java:275)
        at com.oltpbenchmark.api.BenchmarkModule.initTransactionType(BenchmarkModule.java:360)
        at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:269)
Caused by: java.lang.ClassNotFoundException: com.oltpbenchmark.benchmarks.tpcc.procedures.NEW_ORDER
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.oltpbenchmark.util.ClassUtil.getClass(ClassUtil.java:273)
        ... 2 more
```

**Comment by ElBarto90** [comment]
maybe try this config. But plz make sure that you enter your IP/hostname, port, Username, Password, db-name


<?xml version="1.0"?>
<parameters>
	
    
   <dbtype>postgres</dbtype>
    <driver>org.postgresql.Driver</driver>
    <DBUrl>jdbc:postgresql://"YOUR DB IP">:5432</DBUrl>
    <DBName>"YOUR DB NAME"</DBName>
    <username>"YOUR USERNAME"</username>
    <password>"YOUR PW"</password>
    <isolation>TRANSACTION_SERIALIZABLE</isolation>
    
    
    <scalefactor>1</scalefactor>
    
    
    <terminals>1</terminals>
    <works>
        <work>
          <time>60</time>
          <rate>10000</rate>
          <weights>20,20,20,20,20</weights>
        </work>
	</works>
	
	  	
   	<transactiontypes>
    	<transactiontype>
    		<name>NewOrder</name>
    	</transactiontype>
    	<transactiontype>
    		<name>Payment</name>
    	</transactiontype>
    	<transactiontype>
    		<name>OrderStatus</name>
    	</transactiontype>
    	<transactiontype>
    		<name>Delivery</name>
    	</transactiontype>
    	<transactiontype>
    		<name>StockLevel</name>
    	</transactiontype>
   	</transactiontypes>	
</parameters>

**Comment by ElBarto90** [comment]
ok, second try... damn markdown...
try this one maybe and make sure to enter all required information in the upper part (like PASSWORD, HOSTNAME...)

<?xml version="1.0"?>
<parameters>
	
    
    <dbtype>postgres</dbtype>
    <driver>org.postgresql.Driver</driver>
    <DBUrl>jdbc:postgresql://"YOUR HOSTNAME":5432/"YOUR DB/SCHEMA NAME"/</DBUrl>
    <username>"USER"</username>
    <password>"PASSWORD"</password>
    <isolation>TRANSACTION_SERIALIZABLE</isolation>
    
    
    <scalefactor>1</scalefactor>
    
    
    <terminals>1</terminals>
    <works>
        <work>
          <time>60</time>
          <rate>unlimited</rate>
          <weights>20,20,20,20,20</weights>
        </work>
	</works>
	
	  	
   	<transactiontypes>
    	<transactiontype>
    		<name>NewOrder</name>
    	</transactiontype>
    	<transactiontype>
    		<name>Payment</name>
    	</transactiontype>
    	<transactiontype>
    		<name>OrderStatus</name>
    	</transactiontype>
    	<transactiontype>
    		<name>Delivery</name>
    	</transactiontype>
    	<transactiontype>
    		<name>StockLevel</name>
    	</transactiontype>
   	</transactiontypes>	
</parameters>

**Comment by nona89** [comment]
how can i updated on this is file 



<dbtype>postgres</dbtype>
<driver>org.postgresql.Driver</driver>
<DBUrl>jdbc:postgresql://"YOUR HOSTNAME":5432/"YOUR DB/SCHEMA NAME"/</DBUrl>
<username>"USER"</username>
<password>"PASSWORD"</password>
<isolation>TRANSACTION_SERIALIZABLE</isolation>


<scalefactor>1</scalefactor>


<terminals>1</terminals>
<works>
    <work>
      <time>60</time>
      <rate>unlimited</rate>
      <weights>20,20,20,20,20</weights>
    </work>
</works>

      
<transactiontypes>
    <transactiontype>
        <name>NewOrder</name>
    </transactiontype>
    <transactiontype>
        <name>Payment</name>
    </transactiontype>
    <transactiontype>
        <name>OrderStatus</name>
    </transactiontype>
    <transactiontype>
        <name>Delivery</name>
    </transactiontype>
    <transactiontype>
        <name>StockLevel</name>
    </transactiontype>
</transactiontypes>

**Comment by nona89** [comment]
How i can updated on sample_pgtpcc_config benchmark?

**Comment by nona89** [comment]
i am so sorry i will try to understand how i can use it
