### ISSUE TITLE
I see chBenchmark do create only 3 tables? It needs 12 tables right?

### ISSUE THREAD

**Issue by jssprasanna** [oltpbenchmark/oltpbench#115]
Is chBenchmark option completely available in OLTPBench? I see that DDL SQL's for chBenchmark do create only 3 tables(nation, region, supplier) as against 12 tables defined by the chBenchmark?

**Comment by alendit** [comment]
Hi, CH-BenCHmark extends TPC-C schema by these 3 tables. The rest of the tables are created by TPC-C create command.

**Comment by jssprasanna** [comment]
Appreciate your help on this, Thanks :-)
