### ISSUE TITLE
Should we need to run TPCC and CHENCHMARK together to simulate both OLTP and OLAP loads?

### ISSUE THREAD

**Issue by jssprasanna** [oltpbenchmark/oltpbench#116]
Hi Experts,
   How to go about running chbenchmark effectively in OLTPBench test bed? Should we need to execute both TPCC and CHBENCHMARK options together, my guess is that OLTP part of workload defined in chBenchmark should come from TPCC and OLAP workload should come from refined 22 TPC-H queries that are presented under com/src/oltpbenchmark/benchmarks/chbenchmark/queries/query[1-22].sql?

If my guess is right can you experts please help me in what way should I simulate chbenchmark workload using OLTPBench? As I see config templates for chbenchmark only specifies OLAP workload in the form of refined TPC-H queries for revised TPC-C schema.

Appreciate your help on this.
By the way, Thanks a ton for such a wonderful tool.

Thanks
  Swamy

**Comment by alendit** [comment]
Hi,
you are right, you have to execute both tpcc and chbenchmark (which describes the OLAP part of the benchmark) in parallel. You can specify multiple benchmarks with `--bench tpcc,chbenchmark`. You can find an example mixed config in `config/mix_config_postgres.xml`. 

If you have further problems, write me at vorona (at) in.tum.de .

**Comment by mustaphach1** [comment]
HI,
I just want to know how to return the script of queries generated and executed by this benchmark, thank you
