### ISSUE TITLE
cannot run 'create tpcc database' on db2

### ISSUE THREAD

**Issue by agoldin1** [oltpbenchmark/oltpbench#119]
Hi, guys,
I did created the tpcc database on db2 . but I cannot run the following command from oltpbench .:
./oltpbenchmark  --bench tpcc --config config/d10507 --create true -verbose

[root@qa-benchmark oltpbench]# ./oltpbenchmark  --bench tpcc --config config/d10507 --create true -verbose
10:09:33,860 (DBWorkload.java:242) INFO  - **********************************************************************************

Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: config/d10507
Type:          DB2
Driver:        com.ibm.db2.jcc.DB2Driver
URL:           jdbc:DB2://10.10.12.123:50122/d10507
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  1.0

10:09:33,862 (DBWorkload.java:243) INFO  - **********************************************************************************
10:09:33,878 (DBWorkload.java:495) INFO  - Creating new TPCC database...
Exception in thread "main" java.lang.RuntimeException: Unexpected error when trying to create the tpcc database
        at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:224)
        at com.oltpbenchmark.DBWorkload.runCreator(DBWorkload.java:685)
        at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:496)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:DB2://10.10.12.123:50122/d10507
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at com.oltpbenchmark.api.BenchmarkModule.makeConnection(BenchmarkModule.java:107)
        at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:220)
        ... 2 more

My config file for db2 d10507:

<?xml version="1.0"?>
<parameters>
  
  <dbtype>db2</dbtype>
  <driver>com.ibm.db2.jcc.DB2Driver</driver>
  <DBUrl>jdbc:db2://10.10.12.123:50122/d10507</DBUrl>
  <DBName>tpcc</DBName>
  <username>db2qa</username>
  <password>qa1234</password>
  <terminals>100</terminals>
  <works>
    <work>
      <time>3600</time>
      <rate>100</rate>
      <weights>20,20,20,20,20</weights>
      
    </work>
  </works>
  
  <scalefactor>1</scalefactor>
  <dialect>config/dialects/tpcc_dialects.xml</dialect>
  <isolation>TRANSACTION_SERIALIZABLE</isolation>
  <transactiontypes>
    <transactiontype>
      <name>NewOrder</name>
      <id>1</id>
    </transactiontype>
    <transactiontype>
      <name>Payment</name>
      <id>2</id>
    </transactiontype>
    <transactiontype>
      <name>OrderStatus</name>
      <id>3</id>
    </transactiontype>
    <transactiontype>
      <name>Delivery</name>
      <id>4</id>
    </transactiontype>
    <transactiontype>
      <name>StockLevel</name>
      <id>5</id>
    </transactiontype>
  </transactiontypes>
</parameters>

And I have  the driver for db2 10.5 and on machine of db2 and on machine of oltpbench.

What to do with this?

Thank you !

**Comment by apavlo** [comment]
Did you put "db2jcc4.jar" in the `lib` directory? We have definitely used the framework with DB2.

**Comment by agoldin1** [comment]
Yes, I did.


Отправлено со смартфона Samsung Galaxy.


-------- Исходное сообщение --------
От: Andy Pavlo <notifications@github.com>
Дата: 28.07.2016 2:55 (GMT+02:00)
Кому: oltpbenchmark/oltpbench <oltpbench@noreply.github.com>
Копия: "Goldin, Alice" <alice.goldin@intel.com>, Author <author@noreply.github.com>
Тема: Re: [oltpbenchmark/oltpbench] cannot run 'create tpcc database' on db2 (#119)


Did you put "db2jcc4.jar" in the lib directory? We have definitely used the framework with DB2.

**Comment by apavlo** [comment]
Actually, try it with ant instead of the command-line script. I don't think that the script is setting the classpath correctly.

`ant execute -Dbenchmark=tpcc -Dconfig=config/d10507 -Dcreate=true`

If that works, then we should just get rid of that script.

**Comment by agoldin1** [comment]
Should run this command from oltp benchmark machine?



Отправлено со смартфона Samsung Galaxy.


-------- Исходное сообщение --------
От: Andy Pavlo <notifications@github.com>
Дата: 28.07.2016 6:05 (GMT+02:00)
Кому: oltpbenchmark/oltpbench <oltpbench@noreply.github.com>
Копия: "Goldin, Alice" <alice.goldin@intel.com>, Author <author@noreply.github.com>
Тема: Re: [oltpbenchmark/oltpbench] cannot run 'create tpcc database' on db2 (#119)


Actually, try it with ant instead of the command-line script. I don't think that the script is setting the classpath correctly.

ant execute -Dbenchmark=tpcc -Dconfig=config/d10507 -Dcreate=true

If that works, then we should just get rid of that script.

**Comment by apavlo** [comment]
Yes, run it on the same machine that you were running the script.

**Comment by agoldin1** [comment]
No, doesn’t work ☹

[root@qa-benchmark oltpbench]# ant execute -Dbenchmark=tpcc -Dconfig=config/d10507 -Dcreate=true
Buildfile: build.xml

execute:
     [java] 08:56:07,959 (DBWorkload.java:242) INFO  - **********************************************************************************
     [java]
     [java] Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
     [java] Configuration: config/d10507
     [java] Type:          DB2
     [java] Driver:        com.ibm.db2.jcc.DB2Driver
     [java] URL:           jdbc:DB2:// 10.10.12.123:50122/d10507
     [java] Isolation:     TRANSACTION_SERIALIZABLE
     [java] Scale Factor:  1.0
     [java]
     [java] 08:56:07,961 (DBWorkload.java:243) INFO  - **********************************************************************************
     [java] 08:56:07,978 (DBWorkload.java:495) INFO  - Creating new TPCC database...
     [java] Exception in thread "main" java.lang.RuntimeException: Unexpected error when trying to create the tpcc database
     [java]     at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:224)
     [java]     at com.oltpbenchmark.DBWorkload.runCreator(DBWorkload.java:685)
     [java]     at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:496)
     [java] Caused by: java.sql.SQLException: No suitable driver found for jdbc:DB2:// 10.10.12.123:50122/d10507
     [java]     at java.sql.DriverManager.getConnection(DriverManager.java:689)
     [java]     at java.sql.DriverManager.getConnection(DriverManager.java:247)
     [java]     at com.oltpbenchmark.api.BenchmarkModule.makeConnection(BenchmarkModule.java:107)
     [java]     at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:220)
     [java]     ... 2 more

BUILD FAILED
/root/oltpbench/build.xml:92: Java returned: 1

Total time: 1 second

**Comment by apavlo** [comment]
Can you try it with SQLite? I think something is wrong with your JDBC jar.

**Comment by agoldin1** [comment]
I did changed the JDBC jar and I have the same problem. 
I don't know what to  do with this...

**Comment by apavlo** [comment]
I will test when I get back to my desk.

**Comment by agoldin1** [comment]
0



Отправлено со смартфона Samsung Galaxy.


-------- Исходное сообщение --------
От: Andy Pavlo <notifications@github.com>
Дата: 28.07.2016 14:45 (GMT+02:00)
Кому: oltpbenchmark/oltpbench <oltpbench@noreply.github.com>
Копия: "Goldin, Alice" <alice.goldin@intel.com>, Author <author@noreply.github.com>
Тема: Re: [oltpbenchmark/oltpbench] cannot run 'create tpcc database' on db2 (#119)


Can you try it with SQLite? I think something is wrong with your JDBC jar.

**Comment by apavlo** [comment]
SQLite is working for me using a fresh install. I think something is wrong with your environment. Here is the sample config file and the SQLite TPC-C DDL: [sqlite-tpcc.zip](https://github.com/oltpbenchmark/oltpbench/files/388778/sqlite-tpcc.zip)

```
pavlo@trajan:/tmp/oltpbench$ ant execute -Dbenchmark=tpcc -Dconfig=config/sqlite_tpcc_config.xml -Dcreate=true -Dload=true
Buildfile: /tmp/oltpbench/build.xml

execute:
     [java] 11:50:57,832 (DBWorkload.java:242) INFO  - **********************************************************************************
     [java] 
     [java] Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
     [java] Configuration: config/sqlite_tpcc_config.xml
     [java] Type:          SQLITE
     [java] Driver:        org.sqlite.JDBC
     [java] URL:           jdbc:sqlite:/tmp/tpcc.db
     [java] Isolation:     TRANSACTION_SERIALIZABLE
     [java] Scale Factor:  2.0
     [java] 
     [java] 11:50:57,834 (DBWorkload.java:243) INFO  - **********************************************************************************
     [java] 11:50:57,845 (DBWorkload.java:495) INFO  - Creating new TPCC database...
     [java] 11:50:58,001 (DBWorkload.java:497) INFO  - Finished!
     [java] 11:50:58,002 (DBWorkload.java:498) INFO  - **********************************************************************************
     [java] 11:50:58,003 (DBWorkload.java:521) INFO  - Loading data into TPCC database...
     [java] 11:51:19,874 (DBWorkload.java:523) INFO  - Finished!
     [java] 11:51:19,874 (DBWorkload.java:524) INFO  - **********************************************************************************
     [java] 11:51:19,875 (DBWorkload.java:646) INFO  - Skipping benchmark workload execution
BUILD SUCCESSFUL
Total time: 22 seconds
```

**Comment by agoldin1** [comment]
Yes.,  you rigth .I understand  rhat I have problem with JDBC .  But I don't understand what is  this  can be....


Отправлено со смартфона Samsung Galaxy.


-------- Исходное сообщение --------
От: Andy Pavlo <notifications@github.com>
Дата: 28.07.2016 18:54 (GMT+02:00)
Кому: oltpbenchmark/oltpbench <oltpbench@noreply.github.com>
Копия: "Goldin, Alice" <alice.goldin@intel.com>, Author <author@noreply.github.com>
Тема: Re: [oltpbenchmark/oltpbench] cannot run 'create tpcc database' on db2 (#119)


SQLite is working for me using a fresh install. I think something is wrong with your environment. Here is the sample config file and the SQLite TPC-C DDL: sqlite-tpcc.zip<https://github.com/oltpbenchmark/oltpbench/files/388778/sqlite-tpcc.zip>

pavlo@trajan:/tmp/oltpbench$ ant execute -Dbenchmark=tpcc -Dconfig=config/sqlite_tpcc_config.xml -Dcreate=true -Dload=true
Buildfile: /tmp/oltpbench/build.xml

execute:
     [java] 11:50:57,832 (DBWorkload.java:242) INFO  - **********************************************************************************
     [java]
     [java] Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
     [java] Configuration: config/sqlite_tpcc_config.xml
     [java] Type:          SQLITE
     [java] Driver:        org.sqlite.JDBC
     [java] URL:           jdbc:sqlite:/tmp/tpcc.db
     [java] Isolation:     TRANSACTION_SERIALIZABLE
     [java] Scale Factor:  2.0
     [java]
     [java] 11:50:57,834 (DBWorkload.java:243) INFO  - **********************************************************************************
     [java] 11:50:57,845 (DBWorkload.java:495) INFO  - Creating new TPCC database...
     [java] 11:50:58,001 (DBWorkload.java:497) INFO  - Finished!
     [java] 11:50:58,002 (DBWorkload.java:498) INFO  - **********************************************************************************
     [java] 11:50:58,003 (DBWorkload.java:521) INFO  - Loading data into TPCC database...
     [java] 11:51:19,874 (DBWorkload.java:523) INFO  - Finished!
     [java] 11:51:19,874 (DBWorkload.java:524) INFO  - **********************************************************************************
     [java] 11:51:19,875 (DBWorkload.java:646) INFO  - Skipping benchmark workload execution
BUILD SUCCESSFUL
Total time: 22 seconds
