### ISSUE TITLE
how i can display this result by Graph 

### ISSUE THREAD

**Issue by nona89** [oltpbenchmark/oltpbench#125]
transaction type (index in config file), start time (microseconds),latency (microseconds),worker id(start number), phase id(index in config file) 
3,         1470729390.824962,          722254,          1          ,0 
2,1470729390.825292,688809,0,0 
3,1470729390.825303,1490978,0,0 
2,1470729390.825313,1590872,1,0 
6,1470729391.315745,3592855,0,0 
3,1470729391.373542,1267036,1,0 
3,1470729391.640777,1179686,1,0 
6,1470729391.821453,1002414,1,0 
5,1470729391.825958,1277867,1,0 
3,1470729392.104152,1116711,1,0 
2,1470729392.221174,1260244,1,0 
3,1470729392.493961,1180732,1,0 
2,1470729392.674392,1491548,1,0 
6,1470729393.165739,1003044,1,0 
3,1470729393.168945,1097580,1,0 
3,1470729393.266637,1183654,1,0 
3,1470729393.450840,1191573,1,0 
3,1470729393.642113,1100608,1,0 
4,1470729393.743557,1008522,1,0 
2,1470729393.752119,1232042,1,0 
2,1470729393.908037,1594693,0,0 
2,1470729393.984812,1634959,1,0 
2,1470729394.502164,1709371,0,0 
3,1470729394.620032,1233749,1,0 
3,1470729394.852964,1174789,1,0 
2,1470729395.027963,1578688,1,0 
3,1470729395.210828,1271371,0,0 
5,1470729395.482103,2432832,0,0 
3,1470729395.606639,1139433,1,0 
3,1470729395.745678,1209150,1,0 
3,1470729395.954861,1042044,1,0 
3,1470729395.997514,1107959,1,0 
2,1470729396.105463,1374932,1,0 
2,1470729396.480236,1133881,1,0 
3,1470729396.614199,1075669,1,0 
2,1470729396.690030,1285378,1,0 
3,1470729396.914661,1086615,0,0 
5,1470729396.975553,1060111,1,0 
3,1470729397.001610,1285868,0,0 
3,1470729397.035777,1112924,1,0 
3,1470729397.149045,1138435,1,0 
2,1470729397.287225,1774374,0,0 
3,1470729397.287225,1255800,1,0 
3,1470729397.542062,1109482,1,0 
3,1470729397.651184,1092644,1,0 
3,1470729397.744131,1042206,1,0 
3,1470729397.786783,1166799,1,0 
6,1470729397.953424,1002813,1,0 
3,1470729397.956610,1080936,1,0 
3,1470729398.036785,1050846,1,0

**Comment by apavlo** [comment]
I'm not sure what you are asking? It's CSV data. Load it into your favorite graphing package/library.

**Comment by nona89** [comment]
after i download the graphing package/library and when i use this command /tpcc-graph-build.sh tpcc-graph-data.txt tpcc-graph.jpg to bulid my graph i have error 
bash: ./tpcc-graph-build.sh: No such file or directory

**Comment by apavlo** [comment]
I don't know what this script `tpcc-graph-build.sh` you are referring to? I don't think that's included in our repo.
