### ISSUE TITLE
CHBenchmark working?

### ISSUE THREAD

**Issue by zhxchen17** [oltpbenchmark/oltpbench#128]
Hi. Thanks for doing the great job first off : )
One thign confused me is that actually when I am trying to do things like:
`./oltpbenchmark -b chbenchmark --config ./config/mix_config_mysql.xml --execute true --create false --load false -s 1`
there is no output for the benchmark.
On the other hand, when I am trying to use 
`./oltpbenchmark -b tpcc,chbenchmark --config ./config/mix_config_mysql.xml --execute true --create false --load false -s 1`
it seems that the output result is very similar to what I have for
`./oltpbenchmark -b tpcc --config ./config/mix_config_mysql.xml --execute true --create false --load false -s 1`
so is CHbenchmark is expected to work for now on master?

**Comment by alendit** [comment]
Hi Sorrow17,

your command to run CHbenchmark seems to be right. The number of OLAP queries in CHbenchmark is drastically lower than then number of OLTP queries, maybe that's why the output seem identical. Look for queries with IDs over 5 in the output, they will belong to the analytical part.

**Comment by Sorrow17** [comment]
Hi alendit,
    Thanks for the help! After checking the output files, I saw that there are only transaction ID from 2-6( I guess they would be the 5 trsactions in tpcc) in the output, so do you have a clue on what's going on here?

**Comment by alendit** [comment]
Just checked it - it runs at least on PostgreSQL. Couple of idea

1. Are there any error messages about the workers not being able to connect to the server?

2. Maybe try PostgreSQL, as far as I remeber, MySQL had problems with some of the queries (the uncommented ones in from the config). Maybe the newer version added some more that don't work.

Maybe post the output of your command here. It definitelly should work :)

**Comment by Sorrow17** [comment]
I see, will give it a try on postgre, thanks!

**Comment by nafseerk** [comment]
@zhxchen17 : So what did you finally do to run the CH benchmark?
And how do we specify the proportion of analytical/transactional queries?

**Comment by zhxchen17** [comment]
@alendit I remembered I just gave it up because the CH benchmark seemed not well maintained for the database I was using :(

**Comment by bryanosborne** [comment]
After testing on MySQL, the CH-Benchmark only appears to run the 22 OLAP queries and not any of the OLTP queries.

**Comment by malingaperera** [comment]
Hi all,
I have trouble loading data to chbenchmark, it stops after creating only 3 tables (nation, region, supplier), any idea how to load them all?
Thanks.

**Comment by bryanosborne** [comment]
Malingaperera,

You must invoke oltpbench with both tpcc and chbenchmark, I.e., 

./oltpbenchmark -b tpcc,chbenchmark --config......

**Comment by malingaperera** [comment]
@bryanosborne Thanks, much appriciated, will try that.
