### ISSUE TITLE
test failures in oraclejdk-9

### ISSUE THREAD

**Issue by grooverdan** [oltpbenchmark/oltpbench#137]
https://travis-ci.org/grooverdan/oltpbench/jobs/211958777

tests failed:
com.oltpbenchmark.api.TestCreateDialects
com.oltpbenchmark.api.TestStatementDialects
 com.oltpbenchmark.benchmarks.auctionmark.TestAuctionMarkBenchmark
com.oltpbenchmark.benchmarks.auctionmark.TestAuctionMarkWorker
com.oltpbenchmark.benchmarks.chbenchmark.TestCHBenCHmark
...

**Comment by apavlo** [comment]
Can you run this locally and get the output for the failed tests? That's a lot of JNI warnings too...

**Comment by grooverdan** [comment]
https://github.com/grooverdan/oltpbench/blob/err-msg-jdk9/jdk-9-err.txt (finally)

<pre>
 $ jdeprscan --class-path build:`find lib -name \*.jar -printf %p:` --release 9  `find build -name \*class`
class com/oltpbenchmark/jdbc/AutoIncrementPreparedStatement uses deprecated method java/sql/PreparedStatement::setUnicodeStream(ILjava/io/InputStream;I)V 
class com/oltpbenchmark/jdbc/AutoIncrementPreparedStatement overrides deprecated method java/sql/PreparedStatement::setUnicodeStream(ILjava/io/InputStream;I)V 
class com/oltpbenchmark/util/EventObserver has method named getObserver having deprecated return type Ljava/util/Observer; 
class com/oltpbenchmark/util/EventObservable$InnerObservable extends deprecated class java/util/Observable 
class com/oltpbenchmark/util/EventObservable$InnerObservable uses deprecated class java/util/Observable 
class com/oltpbenchmark/util/EventObserver$InnerObserver implements deprecated interface java/util/Observer 
class com/oltpbenchmark/util/EventObserver$InnerObserver uses deprecated class java/util/Observer 
class com/oltpbenchmark/util/EventObserver$InnerObserver has method named update having deprecated parameter type Ljava/util/Observable; 
class com/oltpbenchmark/util/json/JSONWriter uses deprecated method java/lang/Double::<init>(D)V 
class com/oltpbenchmark/util/json/JSONArray uses deprecated method java/lang/Character::<init>(C)V 
class com/oltpbenchmark/util/json/JSONArray uses deprecated method java/lang/Double::<init>(D)V 
class com/oltpbenchmark/util/json/JSONArray uses deprecated method java/lang/Integer::<init>(I)V 
class com/oltpbenchmark/util/json/JSONArray uses deprecated method java/lang/Long::<init>(J)V 
class com/oltpbenchmark/util/json/JSONObject uses deprecated method java/lang/Double::<init>(Ljava/lang/String;)V 
class com/oltpbenchmark/util/json/JSONObject uses deprecated method java/lang/Double::<init>(D)V 
class com/oltpbenchmark/util/json/JSONObject uses deprecated method java/lang/Integer::<init>(I)V 
class com/oltpbenchmark/util/json/JSONObject uses deprecated method java/lang/Long::<init>(J)V 
class com/oltpbenchmark/util/json/JSONObject uses deprecated method java/lang/Integer::<init>(Ljava/lang/String;)V 
class com/oltpbenchmark/util/json/JSONObject uses deprecated method java/lang/Long::<init>(Ljava/lang/String;)V 
class com/oltpbenchmark/benchmarks/twitter/util/TransactionSelector uses deprecated method java/io/DataInputStream::readLine()Ljava/lang/String; 
class com/oltpbenchmark/benchmarks/tpch/TPCHLoader$TableLoader uses deprecated method java/sql/Date::<init>(III)V 
</pre>

**Comment by eribeiro** [comment]
Those jni warnings were removed by https://github.com/oltpbenchmark/oltpbench/commit/019d9cf987a0201b5b68c805f60b79120992c283 

Could you see if it works with jdk-9?
