### ISSUE TITLE
Refactor dialects XML

### ISSUE THREAD

**Issue by apavlo** [oltpbenchmark/oltpbench#167]
Instead of having one giant `dialects.xml` file per benchmark, we should add a "dialects" sub-directory and then have separate xml files per DBMS. I want it to look like how we organize different DDL files.

This should be an easy fix.

**Comment by bohanjason** [comment]
Hi Andy, 

I have added a "dialects" sub-directory, and revised a tpcc benchmark for MySQL in the file "sample_tpcc_config_new.xml". Please let me know if there is something wrong with it. If the fix is good, I will organize all benchmark xml files in this way.  

Thanks .
-Bohan

**Comment by apavlo** [comment]
This is not quite what I had in mind. I agree that your proposal is the better way to do this but it will break compatibility with a lot of our testing infrastructure.

I was thinking that we can automatically pick-up the proper file in the benchmark directory without having to change the config files. We do this for the DDL files:

https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/api/BenchmarkModule.java#L176

You will want to change `BenchmarkModule.getSQLDialect()` to make it look like `BenchmarkModule.getDatabaseDDL()`. It should look for a file in the 'dialects' directory inside of the benchmark.

https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/api/BenchmarkModule.java#L201

Using TPC-C as an example, you should create a directory 'src/com/oltpbenchmark/benchmarks/tpcc/dialects'. Then break up the existing 'tpcc-dialects.xml' file into separate files with the name formatted as `{{dbms}}-dialects.xml`:

* 'src/com/oltpbenchmark/benchmarks/tpcc/dialects/oracle-dialects.xml'
* 'src/com/oltpbenchmark/benchmarks/tpcc/dialects/db2-dialects.xml'
* 'src/com/oltpbenchmark/benchmarks/tpcc/dialects/monetdb-dialects.xml'
* 'src/com/oltpbenchmark/benchmarks/tpcc/dialects/sqlserver-dialects.xml'
* 'src/com/oltpbenchmark/benchmarks/tpcc/dialects/timesten-dialects.xml'

See [DatabaseType](https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/types/DatabaseType.java) for the list of valid 

You may want to write a script that automatically splits up the existing dialect files and make the separate ones. Or you can just copy them by hand.

You also need to change the XSD for the Dialects file format. Luckily I left instructions 6 years ago in the file how to do this :-)

https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/api/dialects.xsd#L2-L16
