### ISSUE TITLE
 Could not find or load main class com.oltpbenchmark.DBWorkload

### ISSUE THREAD

**Issue by mustaphach1** [oltpbenchmark/oltpbench#268]
hello ;
i have execute this command to run your program oltpbechmark for tpcc 
./oltpbenchmark -b tpcc -c config/sample_tpcc_config.xml --create=true --load=true --execute=true -s 5 -o outputfile
But i got this error  
Error: Could not find or load main class com.oltpbenchmark.DBWorkload
Caused by: java.lang.ClassNotFoundException: com.oltpbenchmark.DBWorkload

please , how can i fix it ?

**Comment by apavlo** [comment]
Did you compile everything first?

**Comment by mustaphach1** [comment]
i have installed ant appache , and i have insatalled mysql , i can connect to my DBMS my sql through "root" password "root" , i put my project oltpbench in the folder home of my system ubuntu , but when i run 
./oltpbenchmark -b tpcc -c config/sample_tpcc_config.xml --create=true --load=true --execute=true -s 5 -o outputfile in the terminal
 i got this error Could not find or load main class com.oltpbenchmark.DBWorkload

**Comment by apavlo** [comment]
Did you run `ant build` first?

```
$ ant build 
Buildfile: /home/pavlo/Documents/OLTPBenchmark/oltpbench/build.xml

build:
    [mkdir] Created dir: /home/pavlo/Documents/OLTPBenchmark/oltpbench/build/META-INF
     [copy] Copying 1 file to /home/pavlo/Documents/OLTPBenchmark/oltpbench/build/META-INF
    [javac] Compiling 417 source files to /home/pavlo/Documents/OLTPBenchmark/oltpbench/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 warning
     [copy] Copying 118 files to /home/pavlo/Documents/OLTPBenchmark/oltpbench/build
    [mkdir] Created dir: /home/pavlo/Documents/OLTPBenchmark/oltpbench/build/tests
    [javac] Compiling 54 source files to /home/pavlo/Documents/OLTPBenchmark/oltpbench/build/tests
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 warning

BUILD SUCCESSFUL
Total time: 2 seconds
```

**Comment by mustaphach1** [comment]
now , i have another java error ,
Exception in thread "main" java.lang.RuntimeException: Failed to create new instance of TPCCBenchmark
    at com.oltpbenchmark.util.ClassUtil.newInstance(ClassUtil.java:182)
    at com.oltpbenchmark.util.ClassUtil.newInstance(ClassUtil.java:166)
    at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:247)
Caused by: java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 how can i fix it please ?

**Comment by apavlo** [comment]
What version of the JDK are you using?

**Comment by mustaphach1** [comment]
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)

**Comment by apavlo** [comment]
I don't think anybody has tried it on JDK 10. Try it with JDK 8. Or if you fix it to work on JDK 10 please send us a patch.

**Comment by mustaphach1** [comment]
thank you , i will try it with jdk8 and i will give you the results.

**Comment by mustaphach1** [comment]
Hi. Thanks for doing the great job first off : )
i did run your benchmark succefully , but i need to return the workload of sql queries generated by this benchmark , i talk about the queries not about the dialect of queries , thanks a lot.

**Comment by apavlo** [comment]
Use MySQL's General Query Log:

https://dev.mysql.com/doc/refman/8.0/en/query-log.html

**Comment by mustaphach1** [comment]
hello , i tried to generate mixed worload using chbnechmark,tpcc  , but i  noticed that for OLAP queries the benchmark generates only the 22 queries with redundancy , but i want to generate  a large volume of different olap queries, how  can i do it ? thanks
