### ISSUE TITLE
 a large volume of different olap queries

### ISSUE THREAD

**Issue by mustaphach1** [oltpbenchmark/oltpbench#273]
hello , i tried to generate mixed worload using chbnechmark,tpcc  , but i  noticed that for OLAP queries the benchmark generates only the 22 queries with redundancy , but i want to generate  a large volume of different olap queries, how  can i do it ? thanks

**Comment by apavlo** [comment]
I'm not sure what you are asking? TPC-H only has 22 queries.

**Comment by mustaphach1** [comment]
I want to generate a large workload of queries according to the type of the 22 queries, for example : generate  1000 **different** queries depending on the type of 22 queries tpc-h

**Comment by mustaphach1** [comment]
hello , please  are there the type of join queries for tpc-c ? if there are join queries , how can i execute it ?

**Comment by apavlo** [comment]
TPC-C only has one join query
