### ISSUE TITLE
 Trying to add support for VoltDB(NewSQL): tpcc

### ISSUE THREAD

**Issue by thitcc** [oltpbenchmark/oltpbench#293]
I'm trying to run the tpcc benchmark on voltdb. I've tried to use the MySQL configuration parameters and MemSQL. But it was giving errors in the creation of the db, then I've changed the DDL file to a form in which the VoltDB supported. However, I can not find a way to change the code to load the data. I've seen that there is something related to dialects, which files do I need to modify in order for a database with different dialects to work? For example: the usual DROP TABLE IF EXISTS *table name* does not work on VoltDB. DROP TABLE *table name* IF EXISTS works.

**Comment by renatofritola** [comment]
Thiago, did you manage to solve this?
I'm trying the same problem, I can't run tpcc with VoltDB.
