### ISSUE TITLE
Does TATP benchmark uses a non-uniform data distribution?

### ISSUE THREAD

**Issue by malingaperera** [oltpbenchmark/oltpbench#349]
In the TATP documentation, I saw TATP uses a non-uniform data distribution by default. Is that true for OLTP bench? Is there a parameter to switch between uniform or non-uniform data distribution? Is there a way to change the skewness of data? Thanks.

**Comment by apavlo** [comment]
There is no way to switch this easily.

**Comment by malingaperera** [comment]
Thanks.
