### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/log4j/Logger even have set classpath

### ISSUE THREAD

**Issue by ZhengxunWu** [oltpbenchmark/oltpbench#350]
![image](https://user-images.githubusercontent.com/49115231/103029530-fe742e00-4527-11eb-93fc-b31b103b6053.png)

output of echo %classpath% is .;C:\Users\16073\Desktop\db_research\oltpbench\lib\*.jar

OS: windows10

Anyone can help? can't get it fixed for several days.

**Comment by apavlo** [comment]
Did you install the required packages? I don't know whether this works on Windows.

**Comment by ZhengxunWu** [comment]
I installed apache ant and ivy, and run ant resolve, seem all dependencies are installed.
output of run ant resolve:
![image](https://user-images.githubusercontent.com/49115231/103030458-d7b6f700-4529-11eb-8193-6f35524b86a4.png)
would this framework only work on UNIX-like OS? should I also have WSL2 installed, would that work?

**Comment by apavlo** [comment]
I don't know if it should and I don't have any way to test. I don't normally use the `oltpbenchmark` script. I use ant directly.

The shell scripts are only two lines. Try messing around with them and see what's going on.
