### ISSUE TITLE
INFO - Dead lock error with SEATS benchmark

### ISSUE THREAD

**Issue by sambu5** [oltpbenchmark/oltpbench#353]
Hi,
I am executing SEATS benchmark on MySQL in Cloud (on AWS, GCP, Azure) and I am getting dead lock errors while executing SEATS benchmark. Those errors doesn't cause execution fail, and so the question is the following: can I ignore those? Should I consider them and trying to resolve them?
If the error is not "normal", what can I do to avoid them?

This is an example of the error:

ERROR - caught SQLException in SEATSWorker for procedure NewReservation:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction

Thanks so much.
Samuele

**Comment by apavlo** [comment]
This is a normal MySQL thing. It uses 2PL with deadlock detection.
