### ISSUE TITLE
Can I change the operation count of each transaction in YCSB

### ISSUE THREAD

**Issue by xiangyiwen** [oltpbenchmark/oltpbench#356]
I've used YCSB to test a database ,and the log information shows that there's only one operation in each transaction. I want to have 10 operations per transaction , is there any parameter or interface designed to handle this?

**Comment by apavlo** [comment]
No, you have to modify the source code yourself. It should be easy.

We follow the original YCSB spec.

**Comment by xiangyiwen** [comment]
Thank you so much!! Could I ask one more question that where the relevant codes are, which file or files they are in? I've read the source code, but I couldn't find the right place to modify it.

**Comment by xiangyiwen** [comment]
@apavlo
